@extends('Layouts.main')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-xl-12 col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="new-user-info">
                        <div class="row mb-2">
                            <div class="col-md-12">
                                @if (session('fail'))
                                    <div class="alert alert-danger">
                                        {{ session('fail') }}
                                    </div>
                                @endif
                            </div>
                        </div>
                        <form action="@if($form == 'Tambah') /tambah-checksheet-pengecheckan @else /edit-checksheet-pengecheckan/{{$detail->id}} @endif" method="POST">
                        @csrf
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label class="form-label" for="date">Tanggal</label>
                                <input type="date" class="form-control @error('date') is-invalid @enderror" id="date" name="date" value="@if($form === 'Tambah'){{ old('date') }}@elseif($form === 'Edit' || $form === 'Detail'){{$detail->date}}@endif" @if($form === 'Detail') disabled @endif placeholder="Masukkan Tanggal" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label class="form-label" for="part_name">Nama Part</label>
                                {{-- <input type="text" class="form-control @error('part_name') is-invalid @enderror" id="part_name" name="part_name" value="@if($form === 'Tambah'){{ old('part_name') }}@elseif($form === 'Edit' || $form === 'Detail'){{$detail->part_name}}@endif" @if($form === 'Detail') disabled @endif placeholder="Masukkan Nama Part" required> --}}
                                <select name="part_name" id="part_name" class="selectpicker form-control @error('part_name') is-invalid @enderror" data-live-search="true" @if($form === 'Detail') disabled @endif required>
                                    <option value="" selected disabled>-- Pilih --</option>
                                    <option value="PAINTING HANGER RR SPRING MC128400T" @if($form === "Tambah" && old("part_name") === "PAINTING HANGER RR SPRING MC128400T") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING HANGER RR SPRING MC128400T") selected @endif>PAINTING HANGER RR SPRING MC128400T</option>
                                    <option value="PAINTING BRACKET RR SPRING BUMPER MC122993/94" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET RR SPRING BUMPER MC122993/94") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET RR SPRING BUMPER MC122993/94") selected @endif>PAINTING BRACKET RR SPRING BUMPER MC122993/94</option>
                                    <option value="PAINTING BRACKET RR SPRING BUMPER MC122995T/96T" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET RR SPRING BUMPER MC122995T/96T") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET RR SPRING BUMPER MC122995T/96T") selected @endif>PAINTING BRACKET RR SPRING BUMPER MC122995T/96T</option>
                                    <option value="PAINTING HANGER SPRING MC122991T" @if($form === "Tambah" && old("part_name") === "PAINTING HANGER SPRING MC122991T") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING HANGER SPRING MC122991T") selected @endif>PAINTING HANGER SPRING MC122991T</option>
                                    <option value="PAINTING FOR BRACKET CAB HINGE A MK5511647" @if($form === "Tambah" && old("part_name") === "PAINTING FOR BRACKET CAB HINGE A MK5511647") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING FOR BRACKET CAB HINGE A MK5511647") selected @endif>PAINTING FOR BRACKET CAB HINGE A MK5511647</option>
                                    <option value="PAINTING FOR BRACKET CAB HINGE B MK5511648" @if($form === "Tambah" && old("part_name") === "PAINTING FOR BRACKET CAB HINGE B MK5511648") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING FOR BRACKET CAB HINGE B MK5511648") selected @endif>PAINTING FOR BRACKET CAB HINGE B MK5511648</option>
                                    <option value="PAINTING PLATE STIFFNER RH (OKO60)" @if($form === "Tambah" && old("part_name") === "PAINTING PLATE STIFFNER RH (OKO60)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING PLATE STIFFNER RH (OKO60)") selected @endif>PAINTING PLATE STIFFNER RH (OKO60)</option>
                                    <option value="PAINTING HANGER MC 114411" @if($form === "Tambah" && old("part_name") === "PAINTING HANGER MC 114411") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING HANGER MC 114411") selected @endif>PAINTING HANGER MC 114411</option>
                                    <option value="PAINTING HANGER MC 114412" @if($form === "Tambah" && old("part_name") === "PAINTING HANGER MC 114412") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING HANGER MC 114412") selected @endif>PAINTING HANGER MC 114412</option>
                                    <option value="PAINTING BRACKET MC 114413/14" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET MC 114413/14") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET MC 114413/14") selected @endif>PAINTING BRACKET MC 114413/14</option>
                                    <option value="PAINTING BRACKET MC 114415/16" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET MC 114415/16") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET MC 114415/16") selected @endif>PAINTING BRACKET MC 114415/16</option>
                                    <option value="PAINTING PLATE SHIFTENER LH" @if($form === "Tambah" && old("part_name") === "PAINTING PLATE SHIFTENER LH") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING PLATE SHIFTENER LH") selected @endif>PAINTING PLATE SHIFTENER LH</option>
                                    <option value="PAINTING BRACKET HINO 2640" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET HINO 2640") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET HINO 2640") selected @endif>PAINTING BRACKET HINO 2640</option>
                                    <option value="PAINTING HUB CARRY" @if($form === "Tambah" && old("part_name") === "PAINTING HUB CARRY") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING HUB CARRY") selected @endif>PAINTING HUB CARRY</option>
                                    <option value="PAINTING SHACKLE SPRING 50S" @if($form === "Tambah" && old("part_name") === "PAINTING SHACKLE SPRING 50S") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING SHACKLE SPRING 50S") selected @endif>PAINTING SHACKLE SPRING 50S</option>
                                    <option value="PAINTING COVER SUB-ASSY,DISC BRAKE, RR LH EFC-C" @if($form === "Tambah" && old("part_name") === "PAINTING COVER SUB-ASSY,DISC BRAKE, RR LH EFC-C") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING COVER SUB-ASSY,DISC BRAKE, RR LH EFC-C") selected @endif>PAINTING COVER SUB-ASSY,DISC BRAKE, RR LH EFC-C</option>
                                    <option value="PAINTING COVER SUB-ASSY,DISC BRAKE, RR RH EFC-C" @if($form === "Tambah" && old("part_name") === "PAINTING COVER SUB-ASSY,DISC BRAKE, RR RH EFC-C") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING COVER SUB-ASSY,DISC BRAKE, RR RH EFC-C") selected @endif>PAINTING COVER SUB-ASSY,DISC BRAKE, RR RH EFC-C</option>
                                    <option value="PAINTING BRACKET ENGINE MOUNTING RR TMMIN 12315-889YL" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET ENGINE MOUNTING RR TMMIN 12315-889YL") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET ENGINE MOUNTING RR TMMIN 12315-889YL") selected @endif>PAINTING BRACKET ENGINE MOUNTING RR TMMIN 12315-889YL</option>
                                    <option value="PAINTING BRACKET BZ060 (12311-BZ060)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET BZ060 (12311-BZ060)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET BZ060 (12311-BZ060)") selected @endif>PAINTING BRACKET BZ060 (12311-BZ060)</option>
                                    <option value="PAINTING BRACKET ENGINE MOUNTING (BZ-120)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET ENGINE MOUNTING (BZ-120)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET ENGINE MOUNTING (BZ-120)") selected @endif>PAINTING BRACKET ENGINE MOUNTING (BZ-120)</option>
                                    <option value="PAINTING BRACKET ENGINE MOUNTING RH D73 (12315-BZ090)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET ENGINE MOUNTING RH D73 (12315-BZ090)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET ENGINE MOUNTING RH D73 (12315-BZ090)") selected @endif>PAINTING BRACKET ENGINE MOUNTING RH D73 (12315-BZ090)</option>
                                    <option value="PAINTING BRACKET ENGINE MOUNTING LH D30D (12325-BZ090-H)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET ENGINE MOUNTING LH D30D (12325-BZ090-H)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET ENGINE MOUNTING LH D30D (12325-BZ090-H)") selected @endif>PAINTING BRACKET ENGINE MOUNTING LH D30D (12325-BZ090-H)</option>
                                    <option value="PAINTING BRACKET ENGINE MOUNTING RR D30D (12321-BZ280-H)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET ENGINE MOUNTING RR D30D (12321-BZ280-H)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET ENGINE MOUNTING RR D30D (12321-BZ280-H)") selected @endif>PAINTING BRACKET ENGINE MOUNTING RR D30D (12321-BZ280-H)</option>
                                    <option value="PAINTING BRACKET BD120B-2" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET BD120B-2") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET BD120B-2") selected @endif>PAINTING BRACKET BD120B-2</option>
                                    <option value="PAINTING BRACKET BD-121A-2" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET BD-121A-2") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET BD-121A-2") selected @endif>PAINTING BRACKET BD-121A-2</option>
                                    <option value="PAINTING BRACKET ENGINE MOUNTING RR RH 928 (12321-0U010)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET ENGINE MOUNTING RR RH 928 (12321-0U010)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET ENGINE MOUNTING RR RH 928 (12321-0U010)") selected @endif>PAINTING BRACKET ENGINE MOUNTING RR RH 928 (12321-0U010)</option>
                                    <option value="PAINTING BRACKET ENGINE MOUNTING RR LH 928" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET ENGINE MOUNTING RR LH 928") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET ENGINE MOUNTING RR LH 928") selected @endif>PAINTING BRACKET ENGINE MOUNTING RR LH 928</option>
                                    <option value="PAINTING BRACKET STEARING GEAR (MST)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET STEARING GEAR (MST)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET STEARING GEAR (MST)") selected @endif>PAINTING BRACKET STEARING GEAR (MST)</option>
                                    <option value="PAINTING BRACKET HINO NO 1 EW030 (SINGLE) - MST" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET HINO NO 1 EW030 (SINGLE) - MST") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET HINO NO 1 EW030 (SINGLE) - MST") selected @endif>PAINTING BRACKET HINO NO 1 EW030 (SINGLE) - MST</option>
                                    <option value="PAINTING BRACKET NO 1 RH EW020 (MST)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET NO 1 RH EW020 (MST)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET NO 1 RH EW020 (MST)") selected @endif>PAINTING BRACKET NO 1 RH EW020 (MST)</option>
                                    <option value="PAINTING BRACKET NO 1 LH EW010 (MST)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET NO 1 LH EW010 (MST)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET NO 1 LH EW010 (MST)") selected @endif>PAINTING BRACKET NO 1 LH EW010 (MST)</option>
                                    <option value="PAINTING BRACKET NO 2 SINGLE (EW020)-MST" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET NO 2 SINGLE (EW020)-MST") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET NO 2 SINGLE (EW020)-MST") selected @endif>PAINTING BRACKET NO 2 SINGLE (EW020)-MST</option>
                                    <option value="PAINTING BRACKET NO 2 RH EW020 (MST)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET NO 2 RH EW020 (MST)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET NO 2 RH EW020 (MST)") selected @endif>PAINTING BRACKET NO 2 RH EW020 (MST)</option>
                                    <option value="PAINTING BRACKET NO 2 LH EW020 (MST)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET NO 2 LH EW020 (MST)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET NO 2 LH EW020 (MST)") selected @endif>PAINTING BRACKET NO 2 LH EW020 (MST)</option>
                                    <option value="PAINTING BRACKET NO 3 EW012 (MST)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET NO 3 EW012 (MST)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET NO 3 EW012 (MST)") selected @endif>PAINTING BRACKET NO 3 EW012 (MST)</option>
                                    <option value="PAINTING BRACKET NO 4 EW022 (MST)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET NO 4 EW022 (MST)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET NO 4 EW022 (MST)") selected @endif>PAINTING BRACKET NO 4 EW022 (MST)</option>
                                    <option value="PAINTING BRACKET GY NO 1 RH EW020 (MST)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET GY NO 1 RH EW020 (MST)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET GY NO 1 RH EW020 (MST)") selected @endif>PAINTING BRACKET GY NO 1 RH EW020 (MST)</option>
                                    <option value="PAINTING BRACKET GY NO 1 LH EW020 (MST)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET GY NO 1 LH EW020 (MST)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET GY NO 1 LH EW020 (MST)") selected @endif>PAINTING BRACKET GY NO 1 LH EW020 (MST)</option>
                                    <option value="PAINTING BRACKET GY NO 2" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET GY NO 2") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET GY NO 2") selected @endif>PAINTING BRACKET GY NO 2</option>
                                    <option value="PAINTING STAY ASSY MANIFOLD BZ020 (NO.2)" @if($form === "Tambah" && old("part_name") === "PAINTING STAY ASSY MANIFOLD BZ020 (NO.2)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING STAY ASSY MANIFOLD BZ020 (NO.2)") selected @endif>PAINTING STAY ASSY MANIFOLD BZ020 (NO.2)</option>
                                    <option value="PAINTING STAY MANIFOLD BZ220 (NO.1)" @if($form === "Tambah" && old("part_name") === "PAINTING STAY MANIFOLD BZ220 (NO.1)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING STAY MANIFOLD BZ220 (NO.1)") selected @endif>PAINTING STAY MANIFOLD BZ220 (NO.1)</option>
                                    <option value="PAINTING BRACKET COMPRESOR (BZ140)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET COMPRESOR (BZ140)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET COMPRESOR (BZ140)") selected @endif>PAINTING BRACKET COMPRESOR (BZ140)</option>
                                    <option value="PAINTING BRACKET COMPRESOR (BZ130)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET COMPRESOR (BZ130)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET COMPRESOR (BZ130)") selected @endif>PAINTING BRACKET COMPRESOR (BZ130)</option>
                                    <option value="PAINTING BRACKET GENERATOR (Y4L)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET GENERATOR (Y4L)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET GENERATOR (Y4L)") selected @endif>PAINTING BRACKET GENERATOR (Y4L)</option>
                                    <option value="PAINTING BRACKET GENERATOR (YHA)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET GENERATOR (YHA)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET GENERATOR (YHA)") selected @endif>PAINTING BRACKET GENERATOR (YHA)</option>
                                    <option value="PAINTING BRACKET GENERATOR (YLO)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET GENERATOR (YLO)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET GENERATOR (YLO)") selected @endif>PAINTING BRACKET GENERATOR (YLO)</option>
                                    <option value="PAINTING BRACKET CONTROL CABLE (33524)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET CONTROL CABLE (33524)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET CONTROL CABLE (33524)") selected @endif>PAINTING BRACKET CONTROL CABLE (33524)</option>
                                    <option value="PAINTING BRACKET BD 191" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET BD 191") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET BD 191") selected @endif>PAINTING BRACKET BD 191</option>
                                    <option value="PAINTING BRACKET BD 187" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET BD 187") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET BD 187") selected @endif>PAINTING BRACKET BD 187</option>
                                    <option value="PAINTING CAB DIFE 640-A" @if($form === "Tambah" && old("part_name") === "PAINTING CAB DIFE 640-A") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING CAB DIFE 640-A") selected @endif>PAINTING CAB DIFE 640-A</option>
                                    <option value="PAINTING SHACKLE ISUZU" @if($form === "Tambah" && old("part_name") === "PAINTING SHACKLE ISUZU") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING SHACKLE ISUZU") selected @endif>PAINTING SHACKLE ISUZU</option>
                                    <option value="PAINTING BRACKET ENGINE YTB (RH)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET ENGINE YTB (RH)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET ENGINE YTB (RH)") selected @endif>PAINTING BRACKET ENGINE YTB (RH)</option>
                                    <option value="PAINTING BRACKET ENGINE YTB (LH)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET ENGINE YTB (LH)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET ENGINE YTB (LH)") selected @endif>PAINTING BRACKET ENGINE YTB (LH)</option>
                                    <option value="PAINTING BRACKET ENGINE -077 (LH)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET ENGINE -077 (LH)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET ENGINE -077 (LH)") selected @endif>PAINTING BRACKET ENGINE -077 (LH)</option>
                                    <option value="PAINTING BRACKET ENGINE -075 (RH)" @if($form === "Tambah" && old("part_name") === "PAINTING BRACKET ENGINE -075 (RH)") selected @elseif(($form === "Edit" || $form === 'Detail') && $detail->part_name === "PAINTING BRACKET ENGINE -075 (RH)") selected @endif>PAINTING BRACKET ENGINE -075 (RH)</option>
                                </select>
                            </div>
                            <div class="form-group col-md-6">
                                <label class="form-label" for="air_pocket">Air Pocket</label>
                                <input type="number" class="form-control @error('air_pocket') is-invalid @enderror" id="air_pocket" name="air_pocket" value="@if($form === 'Tambah'){{ old('part_name') }}@elseif($form === 'Edit' || $form === 'Detail'){{$detail->air_pocket}}@endif" @if($form === 'Detail') disabled @endif placeholder="Masukkan Air Pocket" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label class="form-label" for="gumpal">Gumpal</label>
                                <input type="number" class="form-control @error('gumpal') is-invalid @enderror" id="gumpal" name="gumpal" value="@if($form === 'Tambah'){{ old('part_name') }}@elseif($form === 'Edit' || $form === 'Detail'){{$detail->gumpal}}@endif" @if($form === 'Detail') disabled @endif placeholder="Masukkan Gumpal" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label class="form-label" for="bercak">Bercak</label>
                                <input type="number" class="form-control @error('bercak') is-invalid @enderror" id="bercak" name="bercak" value="@if($form === 'Tambah'){{ old('part_name') }}@elseif($form === 'Edit' || $form === 'Detail'){{$detail->bercak}}@endif" @if($form === 'Detail') disabled @endif placeholder="Masukkan Bercak" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label class="form-label" for="tipis">Tipis</label>
                                <input type="number" class="form-control @error('tipis') is-invalid @enderror" id="tipis" name="tipis" value="@if($form === 'Tambah'){{ old('part_name') }}@elseif($form === 'Edit' || $form === 'Detail'){{$detail->tipis}}@endif" @if($form === 'Detail') disabled @endif placeholder="Masukkan Tipis" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label class="form-label" for="meler">Meler</label>
                                <input type="number" class="form-control @error('meler') is-invalid @enderror" id="meler" name="meler" value="@if($form === 'Tambah'){{ old('part_name') }}@elseif($form === 'Edit' || $form === 'Detail'){{$detail->meler}}@endif" @if($form === 'Detail') disabled @endif placeholder="Masukkan Meler" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label class="form-label" for="tunggu_repair">Tunggu Repair</label>
                                <input type="number" class="form-control @error('tunggu_repair') is-invalid @enderror" id="tunggu_repair" name="tunggu_repair" value="@if($form === 'Tambah'){{ old('part_name') }}@elseif($form === 'Edit' || $form === 'Detail'){{$detail->tunggu_repair}}@endif" @if($form === 'Detail') disabled @endif placeholder="Masukkan Tunggu Repair" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label class="form-label" for="total_check">Total Check</label>
                                <input type="number" class="form-control @error('total_check') is-invalid @enderror" id="total_check" name="total_check" value="@if($form === 'Tambah'){{ old('part_name') }}@elseif($form === 'Edit' || $form === 'Detail'){{$detail->total_check}}@endif" @if($form === 'Detail') disabled @endif placeholder="Masukkan Total Check" required>
                            </div>

                            <div class="form-group col-md-12">
                                <button type="submit" class="btn btn-primary mb-1">Simpan</button>
                                <a href="{{ route('kelola-checksheet-pengecheckan') }}" class="btn btn-secondary mb-1">Kembali</a>
                            </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
